version: "3.9"

services:
  db:
    image: postgres:15.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_pass!dE
  web:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
volumes:
  .:
  postgres_data:
  static: